name: Lakshana-Pipeline
on: push
jobs:
  my-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run message
        run: echo "Python installed successfully"
